version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "svil"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/admin-webui"
    target-branch: "svil"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/android-companion"
    target-branch: "svil"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "svil"
    schedule:
      interval: "weekly"
