[Seat:*]
autologin-user=hifi
autologin-user-timeout=0
user-session=hifi-kiosk
# Disable screensaver / DPMS / hardware cursor at the X server level
xserver-command=X -s 0 -dpms -nocursor
greeter-hide-users=true
